apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-services
spec:
  selector:
    app: technews-services
  ports:
    - name: rabbit-ui
      protocol: TCP
      port: 15672
      targetPort: 15672

    - name: rabbit-service
      protocol: TCP
      port: 5672
      targetPort: 5672

    - name: event-store
      protocol: TCP
      port: 2113
      targetPort: 2113
