apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-apis
spec:
  selector:
    component: technews-apis
  ports:
    - name: auth-api
      protocol: TCP
      port: 5138
      targetPort: 5138

    - name: core-api
      protocol: TCP
      port: 5142
      targetPort: 5142
