apiVersion: v1
kind: Pod
metadata:
  name: technews-auth-api
  labels:
    component: technews-apis
spec:
  containers:
    - name: technews-auth-api
      image: technews-auth-api:latest
      env:
        - name: TECHNEWS_AUTH_API_DATABASE_CONNECTION_STRING
          value: "Server=cluster-ip-database,1433;Database=TechNewsAuth;User Id=sa;Password=Pass@123;TrustServerCertificate=True; pooling=true"
        - name: ASPNETCORE_URLS
          value: "http://+:5138"
        - name: TECHNEWS_AUTH_API_BROKER_HOST_NAME
          value: "cluster-ip-services"
        - name: TECHNEWS_AUTH_API_BROKER_VIRTUAL_HOST
          value: "/"
        - name: TECHNEWS_AUTH_API_BROKER_USER_NAME
          value: "guest"
        - name: TECHNEWS_AUTH_API_BROKER_PASSWORD
          value: "guest"
        - name: TECHNEWS_AUTH_API_EVENT_STORE_CONNECTION_STRING
          value: "esdb://cluster-ip-services:2113?tls=false"
        - name: TECHNEWS_AUTH_API_ISSUER_NAME
          value: "technews-auth-api"
      imagePullPolicy: Never
      ports:
        - name: default
          containerPort: 5138
          protocol: TCP
