apiVersion: v1
kind: Pod
metadata:
  name: technews-database
  labels:
    app: technews-database
spec:
  containers:
    - name: technews-database
      image: mcr.microsoft.com/mssql/server:2019-latest
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Pass@123"
      ports:
        - name: default
          containerPort: 1433
          protocol: TCP
